services:
  - type: web
    name: gemini-plan-docx
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 1 --threads 2 --timeout 180"
    autoDeploy: true
    envVars:
      - key: APP_NAME
        value: "Gemini Plan DOCX"
      - key: USAGE_DB_PATH
        value: "/tmp/usage.db"
      - key: SECRET_KEY
        generateValue: true
